services:
  postgres:
    image: postgres:15-alpine
    container_name: delivery-agua-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: delivery_agua_dev
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery_user -d delivery_agua_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: delivery-agua-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data_dev:
  redis_data_dev: