services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery-agua-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # Django Settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - LANGUAGE_CODE=${LANGUAGE_CODE:-pt-br}
      - TIME_ZONE=${TIME_ZONE:-America/Sao_Paulo}

      # Superuser Settings
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      
      # WhatsApp Integration - Evolution API
      - EVOLUTION_API_BASE_URL=${EVOLUTION_API_BASE_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - INSTANCE_NAME=${INSTANCE_NAME}
      - WHATSAPP_ADMIN_NUMBER=${WHATSAPP_ADMIN_NUMBER}
      
      # WhatsApp Integration - CallMeBot
      - CALLMEBOT_API_URL=${CALLMEBOT_API_URL}
      - CALLMEBOT_API_KEY=${CALLMEBOT_API_KEY}
      - CALLMEBOT_PHONE_NUMBER=${CALLMEBOT_PHONE_NUMBER}
      
      # Cloudinary Settings
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && uvicorn app.asgi:application --host 0.0.0.0 --port 8000 --workers ${WORKERS:-1} --log-level info"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
