# Generated by Django 5.0 on 2025-09-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], default='pix', max_length=20),
        ),
    ]
