# Generated by Django 5.1 on 2025-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento no MercadoPago', max_length=255, null=True),
        ),
    ]
