# Generated by Django 5.1 on 2025-09-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_payment_id'),
    ]

    operations = [
    ]
