# Generated by Django 5.1 on 2025-09-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20250911_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do cliente', max_length=14, null=True),
        ),
    ]
