# Generated by Django 5.1 on 2025-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, help_text='URL do pagamento no MercadoPago (para cartão)', null=True),
        ),
    ]
